# Use the official Python image as the base image
FROM python

# Set the working directory inside the container
WORKDIR /app

# Install Libreoffice
RUN apt-get update -y; apt-get install auto-apt-proxy -y; apt-get install default-jre libreoffice-java-common libreoffice-writer-nogui libreoffice-draw-nogui gunicorn -y

# Copy the requirements file to the container
COPY requirements.txt /tmp/requirements.txt

# Install dependencies
RUN pip install -r /tmp/requirements.txt

# Copy the required font files to the image
COPY ./fonts /usr/local/share/fonts

# Copy the rest of the application code to the container
COPY ./python .

# Specify the command to run your Flask app
CMD ["gunicorn", "--bind", "127.0.0.1:5000", "api:app"]
