# Use the official Python image as the base image
FROM python

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file to the container
COPY requirements.txt requirements.txt

# Install dependencies
RUN pip install -r requirements.txt

# Install Libreoffice
RUN apt-get update -y
RUN apt-get install auto-apt-proxy -y
RUN apt-get install default-jre libreoffice-java-common libreoffice-writer-nogui libreoffice-draw-nogui -y

# Copy the required font files to the image
COPY ./fonts /usr/local/share/fonts

# Copy the rest of the application code to the container
COPY ./python .

# Specify the command to run your Flask app
CMD ["python", "api.py"]
